controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# Homepage inicial
index:
    path: / 
    controller: App\Controller\HomeController::index
