controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# Homepage inicial
index:
    path: / 
    controller: App\Controller\HomeController::index

# Consulta de Pessoas
pessoa_consultar:
    path: /pessoa
    controller: App\Controller\PessoaController::index

# Cadastrar Pessoa
pessoa_cadastrar:
    path: /pessoa/cadastrar
    controller: App\Controller\PessoaController::cadastrar

# Editar Pessoa
pessoa_editar:
    path: /pessoa/editar/{id}
    controller: App\Controller\PessoaController::editar

# Excluir Pessoa
pessoa_excluir:
    path: /pessoa/excluir/{id}
    controller: App\Controller\PessoaController::excluir

# Consulta de Contatos
contato_consultar:
    path: /contato
    controller: App\Controller\PessoaController::index
