controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# Homepage inicial
index:
    path: / 
    controller: App\Controller\HomeController::index

# Cadastro de Pessoa
cadastro_pessoa:
    path: /pessoa/cadastrar
    controller: App\Controller\PessoaController::cadastrar